### ISSUE TITLE
Archive Front-End repository and put new-front-end on noj.tw

### ISSUE THREAD

**Issue by uier** [Normal-OJ/new-front-end#22]
- 我提議封存舊的 Front-End，並使用 new-front-end (v2.noj.tw) 來作為 noj.tw 的網站，v2.noj.tw 則 redirect to noj.tw

在進行前需要確保 new-front-end 有滿足 Front-end 擁有的必須功能，目前還缺少以下：

- [x] Problem Create/Edit/Delete #40 
- [x] Homework Create/Edit/Delete #29 
- [x] Announcement Create/Edit/Delete #27 
- [x] Course Create & Add Members into course #47
- [x] Test data Download #31
